# Generated by Django 2.1.5 on 2019-01-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0003_auto_20190127_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='commentaire',
            new_name='comment',
        ),
    ]
