# Generated by Django 2.1.5 on 2019-01-28 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0004_auto_20190127_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordnym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('mot', models.CharField(max_length=100)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimate', models.IntegerField(default=0)),
                ('translate_word', models.ManyToManyField(to='dico.WordTranslate')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslatenym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('mot_translate', models.CharField(max_length=100)),
                ('ultimate', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='translate_word',
            field=models.ManyToManyField(to='dico.WordTranslate'),
        ),
        migrations.AddField(
            model_name='word',
            name='synonym',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dico.Wordnym'),
        ),
        migrations.AddField(
            model_name='wordtranslate',
            name='synonym',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dico.WordTranslatenym'),
        ),
    ]
