# Generated by Django 2.1.5 on 2019-01-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0005_auto_20190128_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordtranslate',
            name='synonym',
        ),
        migrations.AlterField(
            model_name='word',
            name='synonym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dico.Wordnym'),
        ),
        migrations.DeleteModel(
            name='WordTranslatenym',
        ),
    ]
