# Generated by Django 2.1.5 on 2019-01-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0007_auto_20190129_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='synonym',
            field=models.ManyToManyField(to='dico.Wordnym'),
        ),
    ]
