# Generated by Django 2.1.5 on 2019-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0008_auto_20190129_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordnym',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='wordnym',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wordnym',
            name='translate_word',
        ),
        migrations.AlterField(
            model_name='word',
            name='comment',
            field=models.TextField(default='no comment', null=True),
        ),
    ]
