# Generated by Django 2.1.5 on 2019-01-31 10:52

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0009_auto_20190129_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='date_chalenge',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='word',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='word',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
