# Generated by Django 2.1.5 on 2019-02-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0010_auto_20190131_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordtranslate',
            old_name='mot_translate',
            new_name='mot',
        ),
    ]
