# Generated by Django 2.1.4 on 2019-02-03 16:07

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0011_auto_20190201_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimateScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date_chalenge', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
            ],
        ),
    ]
