# Generated by Django 2.1.4 on 2019-02-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0012_ultimatescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimatescore',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
