# Generated by Django 2.1.5 on 2019-02-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0013_ultimatescore_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultimatescore',
            name='image',
        ),
    ]
