# Generated by Django 2.1.4 on 2019-02-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0015_auto_20190204_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberword',
            old_name='user',
            new_name='username',
        ),
    ]
