# Generated by Django 2.1.4 on 2019-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0016_auto_20190204_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translate_mot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
