# Generated by Django 2.1.4 on 2019-02-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0017_word_translate_mot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translate_mot',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
