# Generated by Django 2.1.4 on 2019-02-04 13:24

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0018_auto_20190204_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_chalenge', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='ultimatescore',
            name='date_chalenge',
        ),
        migrations.RemoveField(
            model_name='ultimatescore',
            name='score',
        ),
        migrations.AddField(
            model_name='ultimatescore',
            name='score',
            field=models.ManyToManyField(to='dico.Score'),
        ),
    ]
