# Generated by Django 2.1.5 on 2019-02-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0020_ultimatescore_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
