# Generated by Django 2.1.5 on 2019-02-06 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0021_auto_20190206_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date_chalenge',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonym',
            field=models.ManyToManyField(blank=True, to='dico.Wordnym'),
        ),
    ]
