# Generated by Django 2.1.5 on 2019-02-06 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0022_auto_20190206_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='date_chalenge',
        ),
        migrations.AddField(
            model_name='word',
            name='date_challenge',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='word',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonym',
            field=models.ManyToManyField(to='dico.Wordnym'),
        ),
    ]
