# Generated by Django 2.1.5 on 2019-02-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0023_auto_20190206_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='date_chalenge',
            new_name='date_challenge',
        ),
        migrations.AlterField(
            model_name='word',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonym',
            field=models.ManyToManyField(blank=True, to='dico.Wordnym'),
        ),
    ]
