# Generated by Django 2.1.5 on 2019-02-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0024_auto_20190206_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberword',
            name='taille_max',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='numberword',
            name='taille_ultime',
            field=models.IntegerField(default=2),
        ),
    ]
