# Generated by Django 2.1.5 on 2019-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0025_auto_20190206_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberword',
            name='taille_max',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='numberword',
            name='taille_ultime',
            field=models.IntegerField(default=10),
        ),
    ]
