# Generated by Django 2.1.5 on 2019-02-12 19:18

import dico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0026_auto_20190212_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimatescore',
            name='image',
            field=models.ImageField(storage=dico.models.OverwriteStorage(), upload_to='dico/static/dico/images'),
        ),
    ]
