# Generated by Django 2.1.5 on 2019-02-18 08:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0027_auto_20190212_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='score_d',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
    ]
