# Generated by Django 2.1.5 on 2019-03-03 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0028_word_score_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberword',
            name='first_connexion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='numberword',
            name='last_connexion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
