# Generated by Django 2.1.5 on 2019-03-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0031_auto_20190304_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.AddField(
            model_name='score',
            name='username',
            field=models.CharField(default='SAGBO Philippe', max_length=100),
            preserve_default=False,
        ),
    ]
