# Generated by Django 2.1.5 on 2019-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0034_auto_20190307_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberword',
            name='passgroupe',
            field=models.CharField(default='yep', max_length=30),
            preserve_default=False,
        ),
    ]
