# Generated by Django 2.1.5 on 2019-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dico', '0036_numberword_groupe_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberword',
            name='passgroupe',
        ),
        migrations.AddField(
            model_name='numberword',
            name='prof',
            field=models.CharField(default='', max_length=30),
        ),
    ]
